# Generated by Django 6.0.6 on 2026-07-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='date',
        ),
    ]
